/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VaralChic.views;

/**
 *
 * @author alice
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        lblTitulo = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        lblNomeCliente = new javax.swing.JLabel();
        lblCpfCliente = new javax.swing.JLabel();
        lblRgCliente = new javax.swing.JLabel();
        lblEnderecoCliente = new javax.swing.JLabel();
        lblFoneCliente = new javax.swing.JLabel();
        lblEmailCliente = new javax.swing.JLabel();
        lblObs = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        txtCpfCliente = new javax.swing.JTextField();
        txtRgCliente = new javax.swing.JTextField();
        txtEnderecoCliente = new javax.swing.JTextField();
        txtFoneCliente = new javax.swing.JTextField();
        txtEmailCliente = new javax.swing.JTextField();
        txtObs = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        lblLogotipo = new javax.swing.JLabel();

        jScrollPane5.setViewportView(jTextPane5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setMinimumSize(new java.awt.Dimension(920, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setText("Cadastro de cliente");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSair.setText("Sair");
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        lblNomeCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeCliente.setText("Nome");
        getContentPane().add(lblNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        lblCpfCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCpfCliente.setText("CPF");
        getContentPane().add(lblCpfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        lblRgCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRgCliente.setText("RG");
        getContentPane().add(lblRgCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        lblEnderecoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEnderecoCliente.setText("Endereço");
        getContentPane().add(lblEnderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        lblFoneCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFoneCliente.setText("Telefone");
        getContentPane().add(lblFoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        lblEmailCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmailCliente.setText("E-mail");
        getContentPane().add(lblEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        lblObs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblObs.setText("Observação");
        getContentPane().add(lblObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        txtNomeCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 500, 30));

        txtCpfCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtCpfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 200, 30));

        txtRgCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtRgCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 200, 30));

        txtEnderecoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtEnderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 500, 30));

        txtFoneCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtFoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 500, 30));

        txtEmailCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 500, 30));

        txtObs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 500, 60));

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 130, 50));

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoVaralChic/VARALCHIC logo.png"))); // NOI18N
        getContentPane().add(lblLogotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JLabel lblCpfCliente;
    private javax.swing.JLabel lblEmailCliente;
    private javax.swing.JLabel lblEnderecoCliente;
    private javax.swing.JLabel lblFoneCliente;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblRgCliente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtEnderecoCliente;
    private javax.swing.JTextField txtFoneCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtObs;
    private javax.swing.JTextField txtRgCliente;
    // End of variables declaration//GEN-END:variables
}
