package VaralChic.views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class CadastroDeUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDeUsuario
     */
    public CadastroDeUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNomeUsuario = new javax.swing.JLabel();
        lblCpfUsuario = new javax.swing.JLabel();
        lblRgUsuario = new javax.swing.JLabel();
        lblEnderecoUsuario = new javax.swing.JLabel();
        lblFoneUsuario = new javax.swing.JLabel();
        lblEmailUsuario = new javax.swing.JLabel();
        lblSenhaUsuario = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        txtCpfUsuario = new javax.swing.JTextField();
        txtRgUsuario = new javax.swing.JTextField();
        txtEnderecoUsuario = new javax.swing.JTextField();
        txtFoneUsuario = new javax.swing.JTextField();
        txtEmailUsuario = new javax.swing.JTextField();
        pswSenhaUsuario = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        btnCadastrarUsuario = new javax.swing.JButton();
        lblLogotipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Usuários");
        setFocusCycleRoot(false);
        setLocation(new java.awt.Point(100, 100));
        setMinimumSize(new java.awt.Dimension(920, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setText("Cadastro de usuário");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        lblNomeUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeUsuario.setText("Nome");
        getContentPane().add(lblNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        lblCpfUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCpfUsuario.setText("CPF");
        getContentPane().add(lblCpfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 30, 20));

        lblRgUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRgUsuario.setText("RG");
        getContentPane().add(lblRgUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        lblEnderecoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEnderecoUsuario.setText("Endereço");
        getContentPane().add(lblEnderecoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, 20));

        lblFoneUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFoneUsuario.setText("Telefone");
        getContentPane().add(lblFoneUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        lblEmailUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmailUsuario.setText("E-mail");
        getContentPane().add(lblEmailUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 50, 20));

        lblSenhaUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSenhaUsuario.setText("Senha");
        getContentPane().add(lblSenhaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 50, 20));

        txtNomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 500, 30));

        txtCpfUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCpfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 500, 30));

        txtRgUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtRgUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 500, 30));

        txtEnderecoUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtEnderecoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 500, 30));

        txtFoneUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtFoneUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 500, 30));

        txtEmailUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtEmailUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 500, 30));

        pswSenhaUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(pswSenhaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 500, 30));

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSair.setText("Sair");
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));

        btnCadastrarUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrarUsuario.setText("Cadastrar");
        getContentPane().add(btnCadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 130, 50));

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoVaralChic/VARALCHIC logo.png"))); // NOI18N
        getContentPane().add(lblLogotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarUsuario;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblCpfUsuario;
    private javax.swing.JLabel lblEmailUsuario;
    private javax.swing.JLabel lblEnderecoUsuario;
    private javax.swing.JLabel lblFoneUsuario;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblRgUsuario;
    private javax.swing.JLabel lblSenhaUsuario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField pswSenhaUsuario;
    private javax.swing.JTextField txtCpfUsuario;
    private javax.swing.JTextField txtEmailUsuario;
    private javax.swing.JTextField txtEnderecoUsuario;
    private javax.swing.JTextField txtFoneUsuario;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtRgUsuario;
    // End of variables declaration//GEN-END:variables
}
