package VaralChic.views;

public class frmPaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public frmPaginaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JLabel();
        btnGerencUsuario = new javax.swing.JButton();
        btnGerencCliente = new javax.swing.JButton();
        btnControleVendas = new javax.swing.JButton();
        btnGerencProduto = new javax.swing.JButton();
        lblLogotipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setMinimumSize(new java.awt.Dimension(920, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTitulo.setText("Página principal");
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 25, -1, -1));

        btnGerencUsuario.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnGerencUsuario.setText("Gerenciamento de usuário");
        btnGerencUsuario.setFocusable(false);
        btnGerencUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerencUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerencUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 170, 252, 100));

        btnGerencCliente.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnGerencCliente.setText("Gerenciamento de cliente");
        btnGerencCliente.setFocusable(false);
        btnGerencCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerencClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerencCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 170, 252, 100));

        btnControleVendas.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnControleVendas.setText("Controle de Vendas");
        btnControleVendas.setFocusable(false);
        btnControleVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControleVendasActionPerformed(evt);
            }
        });
        getContentPane().add(btnControleVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 330, 252, 100));

        btnGerencProduto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnGerencProduto.setText("Gerenciamento de produto");
        btnGerencProduto.setFocusable(false);
        btnGerencProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerencProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerencProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 330, 252, 100));

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoVaralChic/VARALCHIC logo.png"))); // NOI18N
        getContentPane().add(lblLogotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //GERENCIAMENTO DE USUÁRIO
    private void btnGerencUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerencUsuarioActionPerformed
        // Chamando e abrindo a tela "frmGerencUsuario"
        frmGerencUsuario gerencUser = new frmGerencUsuario();
        gerencUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGerencUsuarioActionPerformed

    //CONTROLE DE VENDAS
    private void btnControleVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControleVendasActionPerformed
        // Chamando e abrindo a tela "frmControleVenda"
        frmControleVenda venda = new frmControleVenda();
        venda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnControleVendasActionPerformed

    //GERENCIAMENTO DE CLIENTE
    private void btnGerencClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerencClienteActionPerformed
        // Chamando e abrindo a tela "frmGerencCliente"
        frmGerencCliente gerencCliente = new frmGerencCliente();
        gerencCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGerencClienteActionPerformed

    //GERENCIAMENTO DE PRODUTO
    private void btnGerencProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerencProdutoActionPerformed
        // Chamando e abrindo a tela "frmGerencProduto"
        frmGerencProduto gerencProduto = new frmGerencProduto();
        gerencProduto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGerencProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnControleVendas;
    private javax.swing.JButton btnGerencCliente;
    private javax.swing.JButton btnGerencProduto;
    private javax.swing.JButton btnGerencUsuario;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
