package VaralChic.views;

public class frmVendaCrediario extends javax.swing.JFrame {

    /**
     * Creates new form VendaCrediario
     */
    public frmVendaCrediario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        txtTitulo = new javax.swing.JLabel();
        lblPagamento = new javax.swing.JLabel();
        lblDataPagamento = new javax.swing.JLabel();
        lblDataNotificacao = new javax.swing.JLabel();
        lblParcelamento = new javax.swing.JLabel();
        lblValorFatura = new javax.swing.JLabel();
        boxPagamento = new javax.swing.JComboBox<>();
        txtDataPagamento = new javax.swing.JTextField();
        txtDataNotificacao = new javax.swing.JTextField();
        boxParcelamento = new javax.swing.JComboBox<>();
        txtValorFatura = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        btnFecharCompra = new javax.swing.JButton();
        lblLogotipo = new javax.swing.JLabel();

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Fechar Comprar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VendaCrediario");
        setBackground(new java.awt.Color(240, 66, 181));
        setLocation(new java.awt.Point(100, 100));
        setMinimumSize(new java.awt.Dimension(920, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTitulo.setText("Venda crediário");
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 25, -1, -1));

        lblPagamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPagamento.setText("Método de Pagamento");
        getContentPane().add(lblPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 126, -1, 36));

        lblDataPagamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDataPagamento.setText("Data de Pagamento");
        getContentPane().add(lblDataPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 208, -1, 36));

        lblDataNotificacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDataNotificacao.setText("Data de Notificação");
        getContentPane().add(lblDataNotificacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, 36));

        lblParcelamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblParcelamento.setText("Parcelamento");
        getContentPane().add(lblParcelamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 290, -1, 36));

        lblValorFatura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorFatura.setText("Valor da fatura");
        getContentPane().add(lblValorFatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, 36));

        boxPagamento.setEditable(true);
        boxPagamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crediário" }));
        boxPagamento.setToolTipText("");
        boxPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(boxPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 128, 362, 36));

        txtDataPagamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDataPagamento.setText("        /       /");
        txtDataPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 210, 123, 36));

        txtDataNotificacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDataNotificacao.setText("        /       /");
        txtDataNotificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNotificacaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataNotificacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 210, 123, 36));

        boxParcelamento.setEditable(true);
        boxParcelamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxParcelamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1x", "2x", "3x", "4x", "5x", " " }));
        boxParcelamento.setToolTipText("");
        boxParcelamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxParcelamentoActionPerformed(evt);
            }
        });
        getContentPane().add(boxParcelamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 160, 36));

        txtValorFatura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtValorFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorFaturaActionPerformed(evt);
            }
        });
        getContentPane().add(txtValorFatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 150, 36));

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 32, -1, -1));

        btnFecharCompra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFecharCompra.setText("Fechar Comprar");
        btnFecharCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharCompraActionPerformed(evt);
            }
        });
        getContentPane().add(btnFecharCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 479, -1, 36));

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoVaralChic/VARALCHIC logo.png"))); // NOI18N
        getContentPane().add(lblLogotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxParcelamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxParcelamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxParcelamentoActionPerformed

    private void txtDataPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataPagamentoActionPerformed

    private void txtDataNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNotificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNotificacaoActionPerformed

    private void boxPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxPagamentoActionPerformed

    private void txtValorFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorFaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorFaturaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnFecharCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharCompraActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVendaCrediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVendaCrediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVendaCrediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVendaCrediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVendaCrediario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxPagamento;
    private javax.swing.JComboBox<String> boxParcelamento;
    private javax.swing.JButton btnFecharCompra;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblDataNotificacao;
    private javax.swing.JLabel lblDataPagamento;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblPagamento;
    private javax.swing.JLabel lblParcelamento;
    private javax.swing.JLabel lblValorFatura;
    private javax.swing.JTextField txtDataNotificacao;
    private javax.swing.JTextField txtDataPagamento;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JTextField txtValorFatura;
    // End of variables declaration//GEN-END:variables
}
