package VaralChic.views;

public class PaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public PaginaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JLabel();
        btnGerenciamentoLogin = new javax.swing.JButton();
        btnCadastroCliente = new javax.swing.JButton();
        btnControleVendas = new javax.swing.JButton();
        btnCadastroProduto = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblLogotipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setMinimumSize(new java.awt.Dimension(920, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTitulo.setText("Página principal");
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 20, -1, -1));

        btnGerenciamentoLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGerenciamentoLogin.setText("Gerenciamento de login");
        btnGerenciamentoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciamentoLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerenciamentoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 170, 250, 100));

        btnCadastroCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadastroCliente.setText("Cadastro de Cliente");
        btnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 170, 250, 100));

        btnControleVendas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnControleVendas.setText("Controle de Vendas");
        btnControleVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControleVendasActionPerformed(evt);
            }
        });
        getContentPane().add(btnControleVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 330, 250, 100));

        btnCadastroProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadastroProduto.setText("Cadastro de Produto");
        btnCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastroProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 330, 250, 100));

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 27, -1, -1));

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoVaralChic/VARALCHIC logo.png"))); // NOI18N
        getContentPane().add(lblLogotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerenciamentoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciamentoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerenciamentoLoginActionPerformed

    private void btnControleVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControleVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnControleVendasActionPerformed

    private void btnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroClienteActionPerformed

    private void btnCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroProdutoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroCliente;
    private javax.swing.JButton btnCadastroProduto;
    private javax.swing.JButton btnControleVendas;
    private javax.swing.JButton btnGerenciamentoLogin;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
